{"name": "test_login_failure[data1]", "status": "passed", "description": "登录失败", "attachments": [{"name": "log", "source": "a43d666e-5672-4767-85fa-a32b5a0cb7a9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '', 'password': 'Zyj888888', 'check': '请输入您的账号'}"}], "start": 1581902907112, "stop": 1581902907337, "uuid": "41744320-2380-4182-a923-f42fcc22b9f5", "historyId": "bccba46b2c35e73247e34e3ee94a561a", "testCaseId": "1b080540a6f1f5f538edbef9b820e3e6", "fullName": "TestCases.test_login.TestLogin#test_login_failure", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-L7JJJ3C"}, {"name": "thread", "value": "2480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}