{"name": "test_login_failure[data0]", "status": "passed", "description": "登录失败", "attachments": [{"name": "log", "source": "aad96366-921c-4cc5-b870-dd155149eef7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '1660215989', 'password': 'Zyj888888', 'check': '用户不存在!'}"}], "start": 1581902905979, "stop": 1581902906848, "uuid": "9175024b-741d-4349-95be-4c4430eba757", "historyId": "3b6b17cacdcb87573f6ffc4113d9ad4b", "testCaseId": "1b080540a6f1f5f538edbef9b820e3e6", "fullName": "TestCases.test_login.TestLogin#test_login_failure", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-L7JJJ3C"}, {"name": "thread", "value": "2480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}